### PR TITLE
Use BrainIO

### PR DESCRIPTION
**Pull request by jjpr-mit**

### CODE REVIEW

**Comment by jjpr-mit** [comment]
trigger

**Comment by jjpr-mit** [comment]
trigger

**Comment by jjpr-mit** [comment]
@mschrimpf Does the Jenkins build of this ever pass?

**Comment by mschrimpf** [comment]
yes, takes a while though. The tests here are the most involved ones because they test everything from model activations through benchmarks to data retrieval

**Review by mschrimpf — APPROVED** [review]

**Pull request merged**
